name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: git submodule update
      run: git submodule update --init --recursive
    - name: cargo install
      run: cargo install --verbose --path .
    - name: cargo test
      run: cargo test --verbose
    - name: bats test
      run: ./bin/bats test/bats/*.bats
