name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cargo build
      run: cargo build --release
    - name: cargo test
      run: cargo test --verbose
    - name: bats test
      run: ./bin/bats test/bats/*.bats
    - name: cargo clippy
      run: cargo clippy --verbose -- --deny warnings
